### ISSUE TITLE
Building

### ISSUE THREAD

**Issue by MathieuARS** [Mimi8298/Supercell.Magic#4]
I can find any project that can be build without any errors....

https://i.imgur.com/CqAx8MH.png

**Comment by justdimaa** [comment]
Apply the changes from here #3

**Comment by MathieuARS** [comment]
Still an error..

https://i.imgur.com/zuYTBvy.png

**Comment by justdimaa** [comment]
Replace 
```csharp
LogicDataTables.GetIntegerValue("StealLimitMid", 0);
``` 
with 
```csharp
this.GetIntegerValue("StealLimitMid", 0);
```

**Comment by MrVitalikS** [comment]
can you give already compiled server, please

**Comment by MathieuARS** [comment]
Now i have this error on the start.bat cmd

https://i.imgur.com/kCbiR0c.png

**Comment by justdimaa** [comment]
You have to start a local webserver create a `supercell` folder and copy the files from the directory `Supercell.Magic-master\www` into the directory. You should be able to access http://127.0.0.1/supercell/environment.json and see a config then.
When you will start the `start.bat` you will face another problem or two.
You need to provide the game assets for the server.
[Download the Clash of Clans APK 9.256.20](https://www.apkmirror.com/apk/supercell/clash-of-clans/clash-of-clans-9-256-20-release/), use WinRAR or similar to open it.
There you will see an assets folder. Copy it into your webserver directory.
Also don't forget to set up a couchbase server and a redis server.
When you set up the couchbase server you either have to use the credentials given in the `environment.json` or you use your own credentials and replace them in the file.
Once you are logged in, head over to `Buckets` and create the following buckets:
`magic-players`, `magic-admin`, `magic-alliances`, `magic-streams`, `magic-seasons`

If you want to use docker compose for it, create a docker compose file where the `start.bat` is located and copy the code below.
I have used the `Supercell.Magic-master\www` directory as the main directory for the webserver.
To access the couchbase server: http://localhost:8091/
`Supercell.Magic-master\docker-compose.yaml`
```yaml
version: '3'

services:
    webserver:
        image: nginx:alpine
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
        volumes:
            - ./www/:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    couchserver:
        image: couchbase:community-6.0.0
        restart: unless-stopped
        ports:
            - "8091:8091"
        volumes:
            - couchbasedb:/opt/couchbase/var
    redisserver:
        image: redis:alpine3.11
        restart: unless-stopped
        ports:
            - "6379:6379"
        volumes:
            - redisdb:/data

volumes:
    couchbasedb:
    redisdb:
```
`Supercell.Magic-master\docker\nginx\conf.d\app.conf`
```
server {
    listen 80;
    error_log  /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;
    root /var/www/;
}
```
